// ============================================================
// routes/chat.js — Chat / Plan Refinement Endpoint
// ============================================================
// WHAT: Handles POST /api/chat. Lets the user refine their plan
//       after it's been generated by re-running only the relevant
//       specialist agent (not the full 8-agent workflow).
//
// WHY THIS ENDPOINT EXISTS:
//   After the plan is generated, the user might want changes:
//     "find me cheaper hotels"
//     "add a cooking class to the itinerary"
//     "I changed my budget to $4000"
//
//   Running all 8 agents again would take ~40 seconds and cost money
//   for changes that only affect one section. This endpoint runs:
//     1. routerAgent  — determines WHICH specialist to re-run (fast, cheap)
//     2. ONE specialist — re-runs with updated params (only what changed)
//     3. orchestrator — rebuilds the full plan with the updated section
//
//   Total: ~15 seconds instead of ~40. Much better UX.
//
// ── PARTIAL WORKFLOW RE-RUN PATTERN ──────────────────────────
//   This is the key architectural lesson in this file.
//   The workflow in plan.js is the "full run" — all 8 agents.
//   The workflow here is the "partial re-run" — only what changed.
//
//   Both use the same agents (imported from the same files).
//   The DIFFERENCE is which agents this file chooses to call.
//   YOUR CODE decides what to run. The LLM doesn't know or care.
//
// ── STREAMING ────────────────────────────────────────────────
//   Same SSE pattern as plan.js:
//     data: {"agent":"router","status":"done","data":{"targetAgent":"hotels"}}\n\n
//     data: {"agent":"hotels","status":"running","data":{}}\n\n
//     data: {"agent":"hotels","status":"done","data":{...}}\n\n
//     data: {"agent":"orchestrator","status":"running","data":{}}\n\n
//     data: {"agent":"complete","status":"done","data":{"plan":"..."}}\n\n
//
//   The frontend listens for these events and:
//   - Updates the targeted agent's card with new content
//   - Updates the full plan with the re-synthesized version
//   - Adds the exchange to the chat history
//
// HOW DATA FLOWS:
//   POST /api/chat { message, tripDetails, agentResults }
//     → routerAgent → { targetAgent, explanation, modifiedParams }
//     → merge modifiedParams into tripDetails
//     → re-run targeted agent with merged tripDetails
//     → orchestrator with all results (updated section)
//     → stream "complete" with new full plan
// ============================================================

import { Router } from 'express';
import { routerAgent } from '../agents/routerAgent.js';
import { flightsAgent } from '../agents/flightsAgent.js';
import { carRentalAgent } from '../agents/carRentalAgent.js';
import { hotelsAgent } from '../agents/hotelsAgent.js';
import { itineraryAgent } from '../agents/itineraryAgent.js';
import { budgetAgent } from '../agents/budgetAgent.js';
import { packingAgent } from '../agents/packingAgent.js';
import { orchestrator } from '../agents/orchestrator.js';

const router = Router();

// [STREAMING] Same sendEvent helper as plan.js — keeps SSE format consistent.
function sendEvent(res, agent, status, data = {}) {
  res.write(`data: ${JSON.stringify({ agent, status, data })}\n\n`);
}

// ============================================================
// [WORKFLOW] POST /api/chat — Partial plan refinement
// ============================================================
// Request body:
//   {
//     message: "find cheaper hotels under $100",
//     tripDetails: { destination, departureCity, startDate, endDate,
//                    travelers, budget, interests },
//     agentResults: {
//       research: {...},   // from original plan run
//       flights: {...},
//       cars: {...},
//       hotels: {...},
//       itinerary: "...",  // markdown string
//       budget: {...},
//       packing: {...}
//     }
//   }
// ============================================================
router.post('/chat', async (req, res) => {

  // [STREAMING] Same SSE headers as plan.js
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.setHeader('Connection', 'keep-alive');
  res.flushHeaders();

  const { message, tripDetails, agentResults } = req.body;

  // Validate — message and tripDetails must be present
  if (!message || !tripDetails || !agentResults) {
    sendEvent(res, 'error', 'error', { message: 'Missing message, tripDetails, or agentResults' });
    res.end();
    return;
  }

  console.log('\n' + '─'.repeat(50));
  console.log(`[chat] User message: "${message}"`);
  console.log('─'.repeat(50));

  try {

    // ── Step 1: Route the message ─────────────────────────────
    // [WORKFLOW] Ask routerAgent which specialist to re-run.
    // This is a cheap Haiku call — ~0.1 seconds.
    sendEvent(res, 'router', 'running', {});
    const routing = await routerAgent(message, tripDetails, agentResults);
    sendEvent(res, 'router', 'done', {
      targetAgent: routing.targetAgent,
      explanation: routing.explanation,
    });

    // ── Handle "general" routing (no agent re-run needed) ─────
    // [WORKFLOW] If the user asked a question rather than requesting
    // a change (e.g. "what is the visa process?"), we don't re-run
    // any specialist. We answer from existing context using orchestrator.
    if (routing.targetAgent === 'general') {
      console.log(`[chat] General question — answering from context`);
      sendEvent(res, 'orchestrator', 'running', {});

      // [AGENT] Use orchestrator to answer the question with context
      // WHY orchestrator: It has the full plan context and can synthesize an answer.
      // We add the user's question as a note for the orchestrator.
      const answerPlan = await orchestrator({
        tripDetails,
        ...agentResults,
        userQuestion: message,  // orchestrator will notice and answer
      });

      sendEvent(res, 'complete', 'done', { plan: answerPlan, targetAgent: 'general' });
      res.end();
      return;
    }

    // ── Step 2: Merge modified params into tripDetails ─────────
    // [WORKFLOW] If the user changed a parameter ("my budget is now $4000"),
    // routerAgent extracted that into modifiedParams.
    // We merge those into tripDetails so the re-run agent uses the new values.
    //
    // WHY SPREAD: We don't mutate the original tripDetails object.
    // We create a new object so the original remains intact.
    const updatedTripDetails = {
      ...tripDetails,
      ...(routing.modifiedParams || {}),  // override only what changed
    };

    if (Object.keys(routing.modifiedParams || {}).length > 0) {
      console.log(`[chat] Applying param changes:`, routing.modifiedParams);
    }

    // ── Step 3: Re-run the targeted specialist agent ──────────
    // [WORKFLOW] Run ONLY the agent the router identified.
    // All other agents' results remain unchanged.
    console.log(`[chat] Re-running: ${routing.targetAgent}`);
    sendEvent(res, routing.targetAgent, 'running', {});

    // [WORKFLOW] Dispatch to the right agent based on targetAgent string.
    // WHY a switch: Same pattern as the tool dispatch in agent loops —
    // a mapping from a string name to the actual function call.
    let updatedResult;
    switch (routing.targetAgent) {
      case 'flights':
        updatedResult = await flightsAgent(updatedTripDetails, agentResults.research);
        break;
      case 'cars':
        updatedResult = await carRentalAgent(updatedTripDetails, agentResults.research);
        break;
      case 'hotels':
        updatedResult = await hotelsAgent(updatedTripDetails, agentResults.research);
        break;
      case 'itinerary':
        updatedResult = await itineraryAgent(updatedTripDetails, agentResults.research);
        break;
      case 'budget':
        updatedResult = await budgetAgent(updatedTripDetails, agentResults.research);
        break;
      case 'packing':
        updatedResult = await packingAgent(
          updatedTripDetails,
          agentResults.research,
          agentResults.itinerary
        );
        break;
      default:
        throw new Error(`Unknown targetAgent: ${routing.targetAgent}`);
    }

    // [STREAMING] Send the updated section immediately
    // The frontend updates just that one agent card
    sendEvent(res, routing.targetAgent, 'done', updatedResult);
    console.log(`[chat] ${routing.targetAgent} re-run complete ✓`);

    // ── Step 4: Rebuild the full plan with orchestrator ───────
    // [WORKFLOW] Merge the updated result into the existing agentResults
    // and re-run orchestrator to produce an updated full plan.
    //
    // WHY RE-RUN ORCHESTRATOR: The full plan document is a synthesis
    // of all sections. If hotels changed, the plan needs to reflect
    // the new hotel recommendations, new budget implications, etc.
    sendEvent(res, 'orchestrator', 'running', {});

    // [WORKFLOW] Build merged results — original results + one updated section
    const mergedResults = {
      ...agentResults,
      [routing.targetAgent]: updatedResult,  // replace just the changed section
    };

    const updatedPlan = await orchestrator({
      tripDetails: updatedTripDetails,
      research: agentResults.research,
      flights: mergedResults.flights,
      cars: mergedResults.cars,
      hotels: mergedResults.hotels,
      itinerary: mergedResults.itinerary,
      budget: mergedResults.budget,
      packing: mergedResults.packing,
    });

    // [STREAMING] Send the complete updated plan
    // targetAgent tells the frontend which card was re-run (for highlighting)
    sendEvent(res, 'complete', 'done', {
      plan: updatedPlan,
      targetAgent: routing.targetAgent,
      updatedResult,
    });

    console.log(`[chat] Plan updated successfully`);
    res.end();

  } catch (error) {
    console.error('[chat] Error:', error.message);
    sendEvent(res, 'error', 'error', { message: error.message });
    res.end();
  }
});

export default router;
